FROM node:18-slim

WORKDIR /app

COPY package*.json ./
RUN npm install --no-audit --no-fund

RUN apt-get update && apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdrm2 \
    libgbm1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxshmfence1 \
    wget \
    --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 8000

CMD ["node","bot.js"]
